/**
 * @wdk-starter/wdk-ui - theme type definitions
 *
 * Canonical shape for runtime theme objects consumed by WdkThemeProvider.
 *
 * Source: docs/phase-1/wdk-ui-component-library-spec.md (Doc 32) Part III
 * Brand-token source-of-truth: packages/wdk-web-core/src/design/tailwind-tokens.ts
 *
 * v1.0 type contract - derived fields (textSecondary, textTertiary, primaryHover,
 * primaryActive) are optional and computed downstream if omitted (w-3 utility).
 */

/** Motion intensity preset. */
export type WdkMotion = 'subtle' | 'standard' | 'playful' | 'none';

/** Glass intensity (backdrop blur for header bars, modal backdrops). */
export type WdkGlass = 'off' | 'subtle' | 'standard' | 'heavy';

/** UI mode (light / dark / system-follow). */
export type WdkMode = 'dark' | 'light' | 'auto';

/** Color palette for a single theme. */
export interface WdkThemeColors {
  /** Brand primary - CTAs, focus rings, selected states. */
  readonly primary: string;
  /** Primary hover state (derived as primary @ 90% lightness if omitted). */
  readonly primaryHover?: string;
  /** Primary active/pressed state (derived as primary @ 80% lightness if omitted). */
  readonly primaryActive?: string;

  /** Surfaces - base is page background; elevated tiers stack upward. */
  readonly bgBase: string;
  readonly bgElevated1: string;
  readonly bgElevated2: string;
  readonly bgElevated3: string;

  /** Primary text on bgBase. */
  readonly textPrimary: string;
  /** Secondary text (derived as primary @ 72% alpha if omitted). */
  readonly textSecondary?: string;
  /** Tertiary text (derived as primary @ 48% alpha if omitted). */
  readonly textTertiary?: string;

  /** Borders. */
  readonly borderSubtle?: string;
  readonly borderDefault?: string;
  readonly borderEmphasis?: string;

  /** Semantic colors. */
  readonly success: string;
  readonly warning: string;
  readonly error: string;
  readonly info: string;
}

/** Typography stack (CSS font-family strings). */
export interface WdkThemeFonts {
  /** Display font - headlines, brand mark. */
  readonly display: string;
  /** Body font - everything else. */
  readonly body: string;
  /** Monospace font - addresses, hashes, code. */
  readonly mono: string;
}

/** Border radius scale (CSS length strings). */
export interface WdkThemeRadius {
  readonly sm: string;
  readonly md: string;
  readonly lg: string;
  readonly xl: string;
}

/**
 * Full theme contract - what WdkThemeProvider accepts and useWdkTheme returns.
 *
 * Every wdk-ui component eventually reads from this shape (via CSS variables
 * generated by the provider in w-3). Developers fork the template and override
 * any subset of these fields; missing optional fields are derived downstream.
 */
export interface WdkTheme {
  readonly colors: WdkThemeColors;
  readonly fonts: WdkThemeFonts;
  readonly radius: WdkThemeRadius;
  readonly motion: WdkMotion;
  readonly glass: WdkGlass;
  readonly mode: WdkMode;
}